In [1]:
##구글드라이브 권한 획득
!apt install -y -qq --fix-broken python-pycurl python-apt 2> /dev/null
!apt install -y -qq software-properties-common module-init-tools 2> /dev/null
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt update -qq 2>&1 > /dev/null
!apt install -y -qq google-drive-ocamlfuse fuse 2> /dev/null

from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
creds = GoogleCredentials.get_application_default()

!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL

from getpass import getpass

vcode = getpass()

!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Suggested packages:
  python-apt-dbg python-apt-doc libcurl4-gnutls-dev python-pycurl-dbg
  python-pycurl-doc
The following NEW packages will be installed:
  python-apt python-pycurl
0 upgraded, 2 newly installed, 0 to remove and 29 not upgraded.
Need to get 194 kB of archives.
After this operation, 873 kB of additional disk space will be used.
Selecting previously unselected package python-apt.
(Reading database ... 160975 files and directories currently installed.)
Preparing to unpack .../python-apt_1.6.5ubuntu0.5_amd64.deb ...
Unpacking python-apt (1.6.5ubuntu0.5) ...
Selecting previously unselected package python-pycurl.
Preparing to unpack .../python-pycurl_7.43.0.1-0.2_amd64.deb ...
Unpacking python-pycurl (7.43.0.1-0.2) ...
Setting up python-pycurl (7.43.0.1-0.2) ...
Setting up python-apt (1.6.5ubuntu0.5) ...
software-properties-common is already the newest version (0.96.24.32.14).
module-init-tools is already the newest version (24-1ubuntu3.5).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

fuse is already the newest version (2.9.7-1ubuntu1).
The following NEW packages will be installed:
  google-drive-ocamlfuse
0 upgraded, 1 newly installed, 0 to remove and 49 not upgraded.
Need to get 1,335 kB of archives.
After this operation, 7,029 kB of additional disk space will be used.
Selecting previously unselected package google-drive-ocamlfuse.
(Reading database ... 161012 files and directories currently installed.)
Preparing to unpack .../google-drive-ocamlfuse_0.7.24-0ubuntu1~ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.24-0ubuntu1~ubuntu18.04.1) ...
Setting up google-drive-ocamlfuse (0.7.24-0ubuntu1~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.

In [81]:
#drive에 경로 생성
!mkdir -p google_drive
!google-drive-ocamlfuse -o nonempty google_drive

In [82]:
#import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#csv파일 불러오기

df = pd.read_csv("google_drive/steamData/userOwned1.csv")
df

        Unnamed: 0    appid  ...  playtime_2weeks            steamid
0                0       10  ...              NaN  76561197960265744
1                1       20  ...              NaN  76561197960265744
2                2       30  ...              NaN  76561197960265744
3                3       40  ...              NaN  76561197960265744
4                4       50  ...              NaN  76561197960265744
...            ...      ...  ...              ...                ...
112159      112159   252950  ...              NaN  76561197960270742
112160      112160   578080  ...              NaN  76561197960270742
112161      112161   736220  ...              NaN  76561197960270742
112162      112162   755790  ...              NaN  76561197960270742
112163      112163  1046930  ...              NaN  76561197960270742

[112164 rows x 5 columns]

In [ ]:
#파일 합치기 테스트
i = 2
filePath = "google_drive/steamData/userOwned" + str(i) + ".csv"
tempFrame = pd.read_csv(filePath)
df = pd.concat([df, tempFrame])
df

       Unnamed: 0    appid  ...  playtime_2weeks            steamid
0               0       10  ...              NaN  76561197960265744
1               1       20  ...              NaN  76561197960265744
2               2       30  ...              NaN  76561197960265744
3               3       40  ...              NaN  76561197960265744
4               4       50  ...              NaN  76561197960265744
...           ...      ...  ...              ...                ...
91747       91747   546560  ...              NaN  76561197960274366
91748       91748  1145360  ...              NaN  76561197960274366
91749       91749  1217060  ...            424.0  76561197960274366
91750       91750   797410  ...              NaN  76561197960274366
91751       91751   203160  ...              NaN  76561197960274366

[203916 rows x 5 columns]

In [ ]:
#파일 합치기
# for i in range (2, 37):
for i in range (2, 10):
  filePath = "google_drive/steamData/userOwned" + str(i) + ".csv"
  tempFrame = pd.read_csv(filePath)
  df = pd.concat([df, tempFrame])
  print("load complete : " + str(i))
df

load complete : 2
load complete : 3
load complete : 4
load complete : 5
load complete : 6
load complete : 7
load complete : 8
load complete : 9

       Unnamed: 0  appid  playtime_forever  playtime_2weeks            steamid
0               0     10                 0              NaN  76561197960265744
1               1     20                 0              NaN  76561197960265744
2               2     30                 0              NaN  76561197960265744
3               3     40                 0              NaN  76561197960265744
4               4     50                 0              NaN  76561197960265744
...           ...    ...               ...              ...                ...
25388       25388     50                 0              NaN  76561197960315562
25389       25389     60                 0              NaN  76561197960315562
25390       25390     70                 0              NaN  76561197960315562
25391       25391    130                 0              NaN  76561197960315562
25392       25392    730                24              NaN  76561197960315562

[511196 rows x 5 columns]

In [ ]:
#합친 파일 저장
df.to_csv("google_drive/steamData/userOwnedConcatRaw1.csv")

In [125]:
#raw data 불러오기
rawData = pd.read_csv("google_drive/steamData/userOwnedConcatRaw.csv")
rawData.head(20)

    Unnamed: 0  Unnamed: 0.1  ...  playtime_2weeks            steamid
0            0             0  ...              NaN  76561197960265744
1            1             1  ...              NaN  76561197960265744
2            2             2  ...              NaN  76561197960265744
3            3             3  ...              NaN  76561197960265744
4            4             4  ...              NaN  76561197960265744
5            5             5  ...              NaN  76561197960265744
6            6             6  ...              NaN  76561197960265744
7            7             7  ...              NaN  76561197960265744
8            8             8  ...              NaN  76561197960265744
9            9             9  ...              NaN  76561197960265744
10          10            10  ...              NaN  76561197960265744
11          11            11  ...              NaN  76561197960265744
12          12            12  ...              NaN  76561197960265744
13          13            13  ...              NaN  76561197960265744
14          14            14  ...              NaN  76561197960265744
15          15            15  ...              NaN  76561197960265744
16          16            16  ...              NaN  76561197960265744
17          17            17  ...              NaN  76561197960265744
18          18            18  ...              NaN  76561197960265744
19          19            19  ...              NaN  76561197960265744

[20 rows x 6 columns]

In [126]:
#outlier제거
rawData = rawData.drop_duplicates(['appid', 'steamid'])
rawData = rawData.drop(columns=['Unnamed: 0'])
rawData = rawData.drop(columns=['Unnamed: 0.1'])

In [127]:
rawData

          appid  playtime_forever  playtime_2weeks            steamid
0            10                 0              NaN  76561197960265744
1            20                 0              NaN  76561197960265744
2            30                 0              NaN  76561197960265744
3            40                 0              NaN  76561197960265744
4            50                 0              NaN  76561197960265744
...         ...               ...              ...                ...
2016819  536270                 0              NaN  76561197964555948
2016820  532210                 0              NaN  76561197964555948
2016821  274520                 0              NaN  76561197964555948
2016822  616560                 0              NaN  76561197964555948
2016823  582660                 0              NaN  76561197964555948

[1913318 rows x 4 columns]

In [105]:
#unique steamid 확인
rawData['steamid'].unique().size

8398

In [106]:
#idList 생성
idList = rawData['steamid'].unique()
idList

array([76561197960265744, 76561197960265754, 76561197960265763, ...,
       76561197964555626, 76561197964555912, 76561197964555948])

In [ ]:
#단일 유저 데이터 정렬
# user = rawData[rawData.steamid == idList[0]]
# user = user.sort_values(by = ['playtime_forever'], ascending=False)
# user.head()

In [ ]:
#플레이시간 시간단위 분할
# user['playtime_forever'] =user['playtime_forever']/60
# user

In [ ]:
#플레이시간에 log 적용
# user['playtime_forever'] = np.log10(user['playtime_forever'])
# user.head(40)

In [107]:
#weight 할당 def
def nonePlaying(playtime_forever, playtime_2weeks, weight):
  #플레이시간 0
  if playtime_forever == float('-inf'):
    weight = 1
  #플레이시간 1시간 이내
  elif playtime_forever < 0:
    weight = -1
  #플레이시간 1시간 이상
  else :
    weight = 2

  if playtime_2weeks >= 60:
    weight = weight + 1
  return weight

In [ ]:
#weight 할당
# user['weight'] = user.apply(lambda x : nonePlaying(x['playtime_forever'], x['weight']), axis = 1)
# user.head()

In [108]:
idList.size

8398

In [109]:
#weight 추가
rawData['weight'] = 0
rawData.head(20)

    appid  playtime_forever  playtime_2weeks            steamid  weight
0      10                 0              NaN  76561197960265744       0
1      20                 0              NaN  76561197960265744       0
2      30                 0              NaN  76561197960265744       0
3      40                 0              NaN  76561197960265744       0
4      50                 0              NaN  76561197960265744       0
5      60                 0              NaN  76561197960265744       0
6      70               260              NaN  76561197960265744       0
7     130                 0              NaN  76561197960265744       0
8      80                 0              NaN  76561197960265744       0
9     100                 0              NaN  76561197960265744       0
10    220                72              NaN  76561197960265744       0
11    240                 0              NaN  76561197960265744       0
12    280                 0              NaN  76561197960265744       0
13    300                 0              NaN  76561197960265744       0
14    320                 0              NaN  76561197960265744       0
15    340                 2              NaN  76561197960265744       0
16    360                 0              NaN  76561197960265744       0
17    380                 0              NaN  76561197960265744       0
18    400                29              NaN  76561197960265744       0
19    420                 0              NaN  76561197960265744       0

In [110]:
#전체 데이터에 weight 부여

users = rawData
users['playtime_forever'] = users['playtime_forever']/60
users['playtime_forever'] = np.log10(users['playtime_forever'])
users['weight'] = users.apply(lambda x : nonePlaying(x['playtime_forever'], x['playtime_2weeks'], x['weight']), axis = 1)
users

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:726: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)

          appid  playtime_forever  playtime_2weeks            steamid  weight
0            10              -inf              NaN  76561197960265744       1
1            20              -inf              NaN  76561197960265744       1
2            30              -inf              NaN  76561197960265744       1
3            40              -inf              NaN  76561197960265744       1
4            50              -inf              NaN  76561197960265744       1
...         ...               ...              ...                ...     ...
2016819  536270              -inf              NaN  76561197964555948       1
2016820  532210              -inf              NaN  76561197964555948       1
2016821  274520              -inf              NaN  76561197964555948       1
2016822  616560              -inf              NaN  76561197964555948       1
2016823  582660              -inf              NaN  76561197964555948       1

[1913318 rows x 5 columns]

In [111]:
users.head(10)

   appid  playtime_forever  playtime_2weeks            steamid  weight
0     10              -inf              NaN  76561197960265744       1
1     20              -inf              NaN  76561197960265744       1
2     30              -inf              NaN  76561197960265744       1
3     40              -inf              NaN  76561197960265744       1
4     50              -inf              NaN  76561197960265744       1
5     60              -inf              NaN  76561197960265744       1
6     70          0.636822              NaN  76561197960265744       2
7    130              -inf              NaN  76561197960265744       1
8     80              -inf              NaN  76561197960265744       1
9    100              -inf              NaN  76561197960265744       1

In [96]:
#raw data 불러오기
rawData = pd.read_csv("google_drive/steamData/userOwnedConcatRaw.csv")
rawData

         Unnamed: 0  Unnamed: 0.1  ...  playtime_2weeks            steamid
0                 0             0  ...              NaN  76561197960265744
1                 1             1  ...              NaN  76561197960265744
2                 2             2  ...              NaN  76561197960265744
3                 3             3  ...              NaN  76561197960265744
4                 4             4  ...              NaN  76561197960265744
...             ...           ...  ...              ...                ...
2016819        7876          7876  ...              NaN  76561197964555948
2016820        7877          7877  ...              NaN  76561197964555948
2016821        7878          7878  ...              NaN  76561197964555948
2016822        7879          7879  ...              NaN  76561197964555948
2016823        7880          7880  ...              NaN  76561197964555948

[2016824 rows x 6 columns]

In [97]:
#unique steamid 확인
users['steamid'].unique().size

8398

In [98]:
#weight 확인
users['weight']

0          2
1          2
2          2
3          2
4          2
          ..
2016819    2
2016820    2
2016821    2
2016822    2
2016823    2
Name: weight, Length: 1913318, dtype: int64

In [23]:
#데이터 병합
result = pd.merge(rawData, users['weight'],right_index=True, left_index=True )
result

          appid  playtime_forever  ...  weight_x  weight_y
0            10              -inf  ...        -2        -2
1            20              -inf  ...        -2        -2
2            30              -inf  ...        -2        -2
3            40              -inf  ...        -2        -2
4            50              -inf  ...        -2        -2
...         ...               ...  ...       ...       ...
2016819  536270              -inf  ...        -2        -2
2016820  532210              -inf  ...        -2        -2
2016821  274520              -inf  ...        -2        -2
2016822  616560              -inf  ...        -2        -2
2016823  582660              -inf  ...        -2        -2

[1913318 rows x 6 columns]

In [99]:
result.head(10)

   appid  playtime_forever  ...  weight_x  weight_y
0     10              -inf  ...        -2        -2
1     20              -inf  ...        -2        -2
2     30              -inf  ...        -2        -2
3     40              -inf  ...        -2        -2
4     50              -inf  ...        -2        -2
5     60              -inf  ...        -2        -2
6     70          0.636822  ...         3         3
7    130              -inf  ...        -2        -2
8     80              -inf  ...        -2        -2
9    100              -inf  ...        -2        -2

[10 rows x 6 columns]

In [26]:
#outlier 제거
# result = result.drop(columns=["Unnamed: 0", "Unnamed: 0.1"])
result = result.drop(columns=["Unnamed: 0", "Unnamed: 0.1"])
result

          appid  playtime_forever  ...  weight_x  weight_y
0            10              -inf  ...        -2        -2
1            20              -inf  ...        -2        -2
2            30              -inf  ...        -2        -2
3            40              -inf  ...        -2        -2
4            50              -inf  ...        -2        -2
...         ...               ...  ...       ...       ...
2016819  536270              -inf  ...        -2        -2
2016820  532210              -inf  ...        -2        -2
2016821  274520              -inf  ...        -2        -2
2016822  616560              -inf  ...        -2        -2
2016823  582660              -inf  ...        -2        -2

[1913318 rows x 6 columns]

In [112]:
#결과 데이터 저장
users.to_csv("google_drive/steamData/userOwnedResult.csv")

In [113]:
#저장된 데이터 확인

dataConfrim = pd.read_csv("google_drive/steamData/userOwnedResult.csv")
dataConfrim = dataConfrim.drop(columns=["Unnamed: 0"])
dataConfrim

          appid  playtime_forever  playtime_2weeks            steamid  weight
0            10              -inf              NaN  76561197960265744       1
1            20              -inf              NaN  76561197960265744       1
2            30              -inf              NaN  76561197960265744       1
3            40              -inf              NaN  76561197960265744       1
4            50              -inf              NaN  76561197960265744       1
...         ...               ...              ...                ...     ...
1913313  536270              -inf              NaN  76561197964555948       1
1913314  532210              -inf              NaN  76561197964555948       1
1913315  274520              -inf              NaN  76561197964555948       1
1913316  616560              -inf              NaN  76561197964555948       1
1913317  582660              -inf              NaN  76561197964555948       1

[1913318 rows x 5 columns]

In [114]:
#유니크 값 확인
dataConfrim.drop_duplicates()

          appid  playtime_forever  playtime_2weeks            steamid  weight
0            10              -inf              NaN  76561197960265744       1
1            20              -inf              NaN  76561197960265744       1
2            30              -inf              NaN  76561197960265744       1
3            40              -inf              NaN  76561197960265744       1
4            50              -inf              NaN  76561197960265744       1
...         ...               ...              ...                ...     ...
1913313  536270              -inf              NaN  76561197964555948       1
1913314  532210              -inf              NaN  76561197964555948       1
1913315  274520              -inf              NaN  76561197964555948       1
1913316  616560              -inf              NaN  76561197964555948       1
1913317  582660              -inf              NaN  76561197964555948       1

[1913318 rows x 5 columns]

In [115]:
#유니크값 저장
noneDuplicate = dataConfrim.drop_duplicates()
noneDuplicate

          appid  playtime_forever  playtime_2weeks            steamid  weight
0            10              -inf              NaN  76561197960265744       1
1            20              -inf              NaN  76561197960265744       1
2            30              -inf              NaN  76561197960265744       1
3            40              -inf              NaN  76561197960265744       1
4            50              -inf              NaN  76561197960265744       1
...         ...               ...              ...                ...     ...
1913313  536270              -inf              NaN  76561197964555948       1
1913314  532210              -inf              NaN  76561197964555948       1
1913315  274520              -inf              NaN  76561197964555948       1
1913316  616560              -inf              NaN  76561197964555948       1
1913317  582660              -inf              NaN  76561197964555948       1

[1913318 rows x 5 columns]

In [116]:
noneDuplicate

          appid  playtime_forever  playtime_2weeks            steamid  weight
0            10              -inf              NaN  76561197960265744       1
1            20              -inf              NaN  76561197960265744       1
2            30              -inf              NaN  76561197960265744       1
3            40              -inf              NaN  76561197960265744       1
4            50              -inf              NaN  76561197960265744       1
...         ...               ...              ...                ...     ...
1913313  536270              -inf              NaN  76561197964555948       1
1913314  532210              -inf              NaN  76561197964555948       1
1913315  274520              -inf              NaN  76561197964555948       1
1913316  616560              -inf              NaN  76561197964555948       1
1913317  582660              -inf              NaN  76561197964555948       1

[1913318 rows x 5 columns]

In [117]:
#행개수 출력
noneDuplicate.shape[0]

1913318

In [118]:
#user index 설정
noneDuplicate = noneDuplicate.sort_values(by = ['steamid'], ascending=True)
noneDuplicate['newsteamid'] = 0

In [119]:
#index 재설정
noneDuplicate.index = range(0, noneDuplicate.shape[0])
noneDuplicate

          appid  playtime_forever  ...  weight  newsteamid
0            10              -inf  ...       1           0
1        919670              -inf  ...       1           0
2        257510          0.667453  ...       2           0
3        319630              -inf  ...       1           0
4         45740              -inf  ...       1           0
...         ...               ...  ...     ...         ...
1913313  214950              -inf  ...       1           0
1913314  254320              -inf  ...       1           0
1913315  243450              -inf  ...       1           0
1913316  255370         -1.301030  ...      -1           0
1913317  582660              -inf  ...       1           0

[1913318 rows x 6 columns]

In [120]:
#id 변환

for i in noneDuplicate.index:
  if i == 0:
    counter = 0
  elif noneDuplicate['steamid'][i-1] != noneDuplicate['steamid'][i]:
    counter = counter + 1   
  noneDuplicate['newsteamid'][i] = counter

noneDuplicate

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

          appid  playtime_forever  ...  weight  newsteamid
0            10              -inf  ...       1           0
1        919670              -inf  ...       1           0
2        257510          0.667453  ...       2           0
3        319630              -inf  ...       1           0
4         45740              -inf  ...       1           0
...         ...               ...  ...     ...         ...
1913313  214950              -inf  ...       1        8397
1913314  254320              -inf  ...       1        8397
1913315  243450              -inf  ...       1        8397
1913316  255370         -1.301030  ...      -1        8397
1913317  582660              -inf  ...       1        8397

[1913318 rows x 6 columns]

In [121]:
noneDuplicate[noneDuplicate['newsteamid'] == 5]

        appid  playtime_forever  ...  weight  newsteamid
4689  1030830              -inf  ...       1           5
4690    39150         -0.209950  ...      -1           5
4691   252950          1.109466  ...       2           5
4692   238960              -inf  ...       1           5
4693  1083500              -inf  ...       1           5
4694      730          2.324899  ...       2           5
4695   109600              -inf  ...       1           5
4696   205790              -inf  ...       1           5
4697    57900              -inf  ...       1           5
4698   218230              -inf  ...       1           5
4699   273110              -inf  ...       1           5
4700   218620              -inf  ...       1           5
4701   353190          0.208620  ...       2           5
4702   232090          0.462398  ...       2           5
4703   232150         -1.079181  ...      -1           5
4704   418460          0.420506  ...       2           5
4705   737230              -inf  ...       1           5
4706   391220          0.548185  ...       2           5
4707   446850              -inf  ...       1           5
4708   739630          0.693140  ...       2           5
4709  1085660              -inf  ...       1           5
4710   203160              -inf  ...       1           5
4711    50130              -inf  ...       1           5
4712   323370              -inf  ...       1           5
4713    10680              -inf  ...       1           5
4714      100              -inf  ...       1           5
4715    43110              -inf  ...       1           5
4716   667720              -inf  ...       1           5
4717       10          2.399962  ...       2           5
4718       20         -0.246672  ...      -1           5
4719       30         -0.187087  ...      -1           5
4720       40              -inf  ...       1           5
4721       50              -inf  ...       1           5
4722       70         -0.664208  ...      -1           5
4723      130              -inf  ...       1           5
4724       80         -1.778151  ...      -1           5
4725      220          1.015639  ...       2           5
4726      240          1.431632  ...       2           5
4727       60         -1.301030  ...      -1           5
4728      340              -inf  ...       1           5
4729     2500              -inf  ...       1           5
4730    11200              -inf  ...       1           5
4731    12520              -inf  ...       1           5
4732    37800              -inf  ...       1           5
4733    34820              -inf  ...       1           5
4734      550          1.670710  ...       2           5
4735    24960          0.066947  ...       2           5
4736    38700              -inf  ...       1           5
4737      320         -0.736759  ...      -1           5
4738    20500         -0.134699  ...      -1           5

[50 rows x 6 columns]

In [122]:
noneDuplicate['steamid'].unique().size

8398

In [123]:
#결과 데이터 저장
noneDuplicate.drop_duplicates().to_csv("google_drive/steamData/userOwnedResult.csv")